Use same mechanism to manage/load check rules
green-code-initiative/ecoCode-ios pull request #20
Opened 2023-11-29 16:51 UTC by zippy1978

This PR is a reworked version of this initial PR: https://github.com/green-code-initiative/ecoCode-ios/pull/16

It fixes https://github.com/green-code-initiative/ecoCode-ios/issues/15

2023-12-11 08:42 UTC, dedece35 commented
Hi @zippy1978,
could you correct the new Code Smell please ?

2023-12-11 09:07 UTC, dedece35 requested changes
Hi @zippy1978,
there is a lot of modification and I saw that core system is upgraded.
If you tested this PR with your real test project and it was ok, thus I will approve the PR (after checking my review comments :p )

2023-12-11 09:07 UTC, dedece35 commented on pom.xml.versionsBackup
> +<?xml version="1.0" encoding="UTF-8"?>
useless file for me

2023-12-11 09:07 UTC, dedece35 commented on sonar-ios-plugin/pom.xml.versionsBackup
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
useless file for me

2023-12-11 09:07 UTC, dedece35 commented on swift-lang/pom.xml.versionsBackup
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
useless file for me

2023-12-11 15:32 UTC, zippy1978 commented on commons-ios/pom.xml.versionsBackup
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
It's a mistake I remove it

2023-12-11 15:34 UTC, zippy1978 commented on commons-ios/src/main/java/io/ecocode/ios/Const.java
> +public class Const {
Nice !
I change it to an interface

2023-12-11 15:34 UTC, zippy1978 commented on swift-lang/pom.xml.versionsBackup
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.
It's a mistake I remove it

2023-12-11 15:35 UTC, zippy1978 commented on pom.xml.versionsBackup
> +<?xml version="1.0" encoding="UTF-8"?>
It's a mistake I remove it

2023-12-11 21:04 UTC, dedece35 approved these changes

2023-12-18 10:33 UTC, dedece35 commented
Hi @zippy1978,
you can now merge this PR :p

2023-12-19 14:24 UTC, merged